### ISSUE TITLE
Missing gitops_exporter.sh

### ISSUE THREAD

**Issue by bartoszmajsak** [mcouliba/debugging-workshop#17]
`GitOps - Export` task refers to `gitops_exporter.sh` script which is nowhere to be found

https://github.com/mcouliba/debugging-workshop/blob/76de08f2d24eb8ae933a6b0a549dea015d17d272/devfile.yaml#L45-L50

I can't find any reference to it besides screenshot in workshop material. If this task is not needed maybe it's better to just remove it?

**Comment by mcouliba** [comment]
This script and command are not used in the workshop.
They were removed from it.
